name: e2e
on:
  pull_request:
  push: { branches: [ release/sprint-pack-02 ] }
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest

    # opcional mas recomendado: define o diretório padrão do job
    defaults:
      run:
        working-directory: telemed-merged

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: telemed-merged/package-lock.json

      - name: Install deps
        run: npm ci --workspaces --include=dev

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build --workspaces --if-present

      - name: Start preview
        # ❗ executa no telemed-merged e escreve PID com caminho absoluto
        run: |
          set -euo pipefail
          ROOT="$GITHUB_WORKSPACE/telemed-merged"
          PIDFILE="$ROOT/server.pid"
          echo "🚀 Starting TeleMed Docs Automation Service (TypeScript)..."
          # usa npx para não depender do tsx instalado no repo
          npx -y tsx watch telemed-docs-automation/src/index.ts &
          echo $! > "$PIDFILE"
          sleep 2

      - name: Sanity - ensure @playwright/test is resolvable
        run: node -e "require('@playwright/test'); console.log('playwright ok')"

      - name: Run Playwright tests
        run: npx playwright test

      - name: Stop servers
        if: always()
        run: |
          set +e
          ROOT="$GITHUB_WORKSPACE/telemed-merged"
          PIDFILE="$ROOT/server.pid"
          if [ -f "$PIDFILE" ]; then
            PID=$(cat "$PIDFILE")
            echo "🛑 Stopping docs automation service ($PID)"
            kill "$PID" || true
            rm -f "$PIDFILE"
          else
            echo "ℹ️ No PID file to stop."
          fi