name: e2e
on:
  push:
    branches: [ release/sprint-pack-02 ]
  pull_request:

defaults:
  run:
    working-directory: telemed-merged

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: telemed-merged/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build

      - name: Start app (primary 5000 → fallback 5173)
        id: start
        run: |
          set -euo pipefail
          (node ../index.js > server.log 2>&1 & echo $! > server.pid) || true
          if npx wait-on -t 20000 http://localhost:5000; then
            echo "base_url=http://localhost:5000" >> $GITHUB_OUTPUT
          else
            npx http-server ../. --port 5173 --silent > server.log 2>&1 &
            npx wait-on -t 20000 http://localhost:5173
            echo "base_url=http://localhost:5173" >> $GITHUB_OUTPUT
          fi

      - name: Debug deps
        run: |
          pwd && ls -la
          node -v && npm -v
          npm ls @playwright/test || true
          sudo ss -ltnp | head -n 20 || true
          tail -n 200 server.log || true

      - name: Sanity: ensure @playwright/test is resolvable
        run: node -e "console.log(require.resolve('@playwright/test'))"

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ steps.start.outputs.base_url }}
          CI: true
        run: npx playwright test --reporter=line

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: telemed-merged/playwright-report